-- ============================================================================
-- Script: 02_security_masking.sql
-- Purpose: Dynamic Column-Level Data Masking & Role-Based Access Control
-- ============================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE BANKING_DB;
USE SCHEMA ANALYTICS;

-- 1. Define PII Data Masking Policy
CREATE OR REPLACE MASKING POLICY ANALYTICS.PII_MASK AS (val STRING) 
RETURNS STRING ->
    CASE 
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'COMPLIANCE_OFFICER') THEN val
        ELSE 'XXXX-XXXX-' || RIGHT(val, 4)
    END;

-- 2. Apply Policy to Sensitive Customer Identification Columns
ALTER TABLE BANKING_DB.ANALYTICS.DIM_CUSTOMER 
MODIFY COLUMN aadhaar_number SET MASKING POLICY ANALYTICS.PII_MASK;

ALTER TABLE BANKING_DB.ANALYTICS.DIM_CUSTOMER 
MODIFY COLUMN pan_number SET MASKING POLICY ANALYTICS.PII_MASK;

-- 3. Configure Business Role Permissions (RBAC)
CREATE ROLE IF NOT EXISTS BI_ANALYST;

GRANT USAGE ON DATABASE BANKING_DB TO ROLE BI_ANALYST;
GRANT USAGE ON SCHEMA BANKING_DB.ANALYTICS TO ROLE BI_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA BANKING_DB.ANALYTICS TO ROLE BI_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA BANKING_DB.ANALYTICS TO ROLE BI_ANALYST;