-- ============================================================================
-- Script: 02_copy_into_raw.sql
-- Purpose: Bulk Load Cleaned Parquet Files from Stage into Raw Tables
-- ============================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE BANKING_DB;
USE SCHEMA PUBLIC;
USE WAREHOUSE COMPUTE_WH;

COPY INTO CUSTOMER_MASTER 
FROM @PUBLIC.BANKING_STAGE/customer_master/
FILE_FORMAT = (FORMAT_NAME = 'PUBLIC.PARQUET_FORMAT') 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO ACCOUNT_MASTER 
FROM @PUBLIC.BANKING_STAGE/account_master/
FILE_FORMAT = (FORMAT_NAME = 'PUBLIC.PARQUET_FORMAT') 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO BRANCH_MASTER 
FROM @PUBLIC.BANKING_STAGE/branch_master/
FILE_FORMAT = (FORMAT_NAME = 'PUBLIC.PARQUET_FORMAT') 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO CARD_MASTER 
FROM @PUBLIC.BANKING_STAGE/card_master/
FILE_FORMAT = (FORMAT_NAME = 'PUBLIC.PARQUET_FORMAT') 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO FD_MASTER 
FROM @PUBLIC.BANKING_STAGE/fd_master/
FILE_FORMAT = (FORMAT_NAME = 'PUBLIC.PARQUET_FORMAT') 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO LOAN_MASTER 
FROM @PUBLIC.BANKING_STAGE/loan_master/
FILE_FORMAT = (FORMAT_NAME = 'PUBLIC.PARQUET_FORMAT') 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO TRANSACTION_MASTER 
FROM @PUBLIC.BANKING_STAGE/transaction_master/
FILE_FORMAT = (FORMAT_NAME = 'PUBLIC.PARQUET_FORMAT') 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;